CHL/CHL/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CHL.Models
{
    
    public class Category : MasterProperty
    {
        public Int64 Id { get; set; }
        public string Name { get; set; }

    }
}

CHL/CHL/Models/Device.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CHL.Models
{
    public class Device
    {
        public string SystemName { get; set; }
        public string ASSETNUMBER { get; set; }
        public string ASSETTYPE { get; set; }
        public string DATEOFPURCHASE { get; set; }
        public string WARRENTYBEGIN { get; set; }
        public string WARRENTYEND { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIALNUMBER { get; set; }
        public string PROCESSORTYPE { get; set; }
        public string HDD { get; set; }
        public string RAM { get; set; }
        public string GRAPHICCARD { get; set; }
        public string CDDVDROAM { get; set; }
        public string LOCATION { get; set; }
        public string PURCHASEPRICE { get; set; }
        public string DISPOSEDDATE { get; set; }
        public string ASSETDEPRECIATION { get; set; }
        public string DEPRECIATIONMETHOD { get; set; }
        public string STATUS { get; set; }
        public string Remarks { get; set; }
        
    }
}

CHL/CHL/Models/MasterProperty.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CHL.Models
{
    
    public class MasterProperty
    {
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Status { get; set; }



    }
}

CHL/CHL/Models/PagingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CHL.Models
{
     
    public class PagingModel<T>
    {
        public int draw { get; set; }
        public int recordsTotal { get; set; }
        public int recordsFiltered { get; set; }
        public T data { get; set; }
    }
}

CHL/CHL/Models/Software.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CHL.Models
{
    public class Software : MasterProperty
    {
        public string Title { get; set; }
        public string SOFTWAREID { get; set; }
        public string SOFTWARETYPE { get; set; }
        public string SOFTWARENAME { get; set; }
        public string LICENCENUMBER { get; set; }
        public string MANUFACTURER { get; set; }
        public string NOOFLICESES { get; set; }
        public string PURCHASEDATE { get; set; }
        public decimal PURCHASEPRICE { get; set; }
        public string PURCHASEDFROM { get; set; }
        public string NEXTRENEWALDATE { get; set; }

    }
}

CHL/CHL/Models/Subcategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CHL.Models
{
    public class Subcategory
    {
        public Int64 Id { get; set; }
        public string Name { get; set; }
    }
}

CHL/CHL/Controllers/DeviceCategoryController.cs
using CHL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHL.Controllers
{
    public class DeviceCategoryController : Controller
    {
        // GET: DeviceCategory
        [HttpGet]
        public ActionResult Category()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category model)
        {
            return Json(true);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category model)
        {
            return Json(true);
        }
        [HttpGet]
        public ActionResult Subcategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddSubcategory(Subcategory model)
        {
            return Json(true);
        }
        [HttpPost]
        public ActionResult UpdateSubcategory(Subcategory model)
        {
            return Json(true);
        }

        [HttpGet]
        public ActionResult GetAllCategory()
        {

            List<Category> categories = new List<Category>{
                       new Category {Name="Computer", Status="Active",CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                       new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                        new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                         new Category {Name="Computer Accessories", Status="Active",CreatedDate=DateTime.Now },
                          new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                           new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                            new Category {Name="Computer Accessories",Status="Active", CreatedDate=DateTime.Now },
                             new Category {Name="Golu",Status="Active", CreatedDate=DateTime.Now },

                   };
            ;
            var listObj = new PagingModel<List<Category>>()
            {
                data = categories.ToList(),
                draw = 1,
                recordsFiltered = 50,
                recordsTotal = 50
            };

            return Json(listObj, JsonRequestBehavior.AllowGet);
        }




    }
}

CHL/CHL/Controllers/DeviceController.cs
using CHL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHL.Controllers
{
    public class DeviceController : Controller
    {
        // GET: Device
        [HttpGet]
        public ActionResult AddDevice()
        {
            return View();
        }
        public ActionResult ViewDevice()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Device model)
        {
            return Json(true);
        }
    }
}

CHL/CHL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CHL/CHL/Controllers/SoftwareController.cs
using CHL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CHL.Controllers
{
    public class SoftwareController : Controller
    {
        // GET: Software
        public ActionResult AddSoftware()
        {
            return View();
        }
        public ActionResult ViewSoftware()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddSoftware(Software model)
        {
            return Json(true);
        }
        
    }
}

CHL/CHL/Views/Device/AddDevice.cshtml
@{
    ViewBag.Title = "AddDevice";
}



<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Add Device</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" method="post" action="/Device/AddDevice" id="frmDevice">
        <div class="box-body">
            <div class="row">
                <div class="col-lg-6">
                    <h4 style="float:right;border-bottom:1px solid">General</h4>
                </div>
                <div class="col-lg-6">

                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="systemName">SYSTEM NAME</label>
                        <input type="text" class="form-control" name="SystemName" id="systemName" placeholder="System Name">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="ASSETNUMBER">ASSET NUMBER</label>
                        <input type="text" class="form-control" name="ASSETNUMBER" id="ASSETNUMBER" placeholder="Asset Number">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="ASSETTYPE">ASSET TYPE</label>
                        <select id="ASSETTYPE" name="ASSETTYPE" class="form-control">
                            <option value="">--Select--</option>
                            <option value="Laptop">Laptop</option>
                            <option value="Desktop">Desktop</option>
                            <option value="Camera">Camera</option>
                        </select>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="DATEOFPURCHASE">DATE OF PURCHASE</label>
                        <input type="text" class="form-control" name="DATEOFPURCHASE" id="DATEOFPURCHASE" placeholder="Date Of Purchage">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="ASSETNUMBER">WARRENTY BEGIN</label>
                        <input type="text" class="form-control" name="WARRENTYBEGIN" id="WARRENTYBEGIN" placeholder="Warrenty Begin">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="WARRENTYEND">WARRENTY END</label>
                        <input type="text" class="form-control" name="WARRENTYEND" id="WARRENTYEND" placeholder="Warrenty End">
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-lg-6">
                    <h4 style="float:right;border-bottom:1px solid">Hardware</h4>
                </div>
                <div class="col-lg-6">

                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="MANUFACTURER">MANUFACTURER</label>
                        <select id="MANUFACTURER" name="MANUFACTURER" class="form-control">
                            <option value="">--Select--</option>
                            <option value="Del">Del</option>
                            <option value="HP">HP</option>
                            <option value="Lenovo">Lenovo</option>
                            <option value="Assembled">Assembled</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="MODEL">MODEL</label>
                        <input type="text" class="form-control" name="MODEL" id="MODEL" placeholder="Model">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="SERIALNUMBER">SERIAL NUMBER</label>
                        <input type="text" class="form-control" name="SERIALNUMBER" id="SERIALNUMBER" placeholder="Serial Number">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="PROCESSORTYPE">PROCESSOR TYPE</label>
                        <input type="text" class="form-control" name="PROCESSORTYPE" id="PROCESSORTYPE" placeholder="Processor Type">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="HDD">HDD</label>
                        <select id="HDD" name="HDD" class="form-control">
                            <option value="">--Select--</option>
                            <option value="500GB">500GB</option>
                            <option value="1TB">1TB</option>
                            <option value="NA">NA</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="RAM">RAM</label>
                        <select id="RAM" name="RAM" class="form-control">
                            <option value="">--Select--</option>
                            <option value="2GB">2GB</option>
                            <option value="4GB">4GB</option>
                            
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="GRAPHICCARD">GRAPHIC CARD</label>
                        <input type="text" class="form-control" name="GRAPHICCARD" id="GRAPHICCARD" placeholder="Graphics Card">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="CDDVDROAM">CD/DVD ROAM</label>
                        <input type="text" class="form-control" name="CDDVDROAM" id="CDDVDROAM" placeholder="Cd/DVD ROAM">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="LOCATION">LOCATION</label>
                        <select id="LOCATION" name="LOCATION" class="form-control">
                            <option value="">--Select--</option>
                            <option value="Noida">Noida</option>
                            <option value="Bangalore">Bangalore</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="PURCHASEPRICE">PURCHASE PRICE</label>
                        <input type="text" class="form-control" name="PURCHASEPRICE" id="PURCHASEPRICE" placeholder="Purchase Price">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="DISPOSEDDATE">DISPOSED DATE</label>
                        <input type="text" class="form-control" name="DISPOSEDDATE" id="DISPOSEDDATE" placeholder="Disposed Date">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="ASSETDEPRECIATION">ASSET DEPRECIATION</label>
                        <textarea class="form-control" rows="3"name="ASSETDEPRECIATION" id="ASSETDEPRECIATION" placeholder="Asset Depreciation"></textarea>
                         
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="DEPRECIATIONMETHOD">DEPRECIATION METHOD</label>
                        <input type="text" class="form-control" name="DEPRECIATIONMETHOD" id="DEPRECIATIONMETHOD" placeholder="Depreciation Method">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="STATUS">STATUS</label>
                        <select id="STATUS" name="STATUS" class="form-control">
                            <option value="">--Select--</option>
                            <option value="New">New</option>
                            <option value="Used">Used</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="Remarks">Remarks</label>
                        <input type="text" class="form-control" name="Remarks" id="Remarks" placeholder="Remarks">
                    </div>
                </div>
            </div>



        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-default">Back To List</button>
            <span class="dangerMesg"></span>
            <span class="successMesg"></span>
            <button type="submit" id="btn-device" class="btn btn-info pull-right">Submit</button>
        </div>
    </form>
</div>

@section scripts
{
    <script src="~/Scripts/AppScript/add-device.js"></script>
    
}

CHL/CHL/Views/Device/ViewDevice.cshtml
@{
    ViewBag.Title = "ViewDevice";
}

<h2>ViewDevice</h2>

CHL/CHL/Views/DeviceCategory/Category.cshtml
@{
    ViewBag.Title = "Category";
}

<div class="box box-info">
    <div class="box-header with-border">
        <div class="row">
            <div class="col-sm-6">
                <h3 class="box-title">Category List</h3>
            </div>
            <div class="col-sm-6">
                <button type="button" data-toggle="modal" data-target="#add_category_model" class="btn btn-sm btn-primary" style="float:right">Add New</button>
            </div>
        </div>
    </div>
    <div class="box-body">
        <div id="tbl_category_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table id="tbl_category" class="table table-hover dataTable table-bordered nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Created Date</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th>Status</th>
                                <th>Created Date</th>
                                <th>Action</th>

                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade noprint" id="del_Opener" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header modal-popup-header">
                <button type="button" class="close" data-dismiss="modal" id="btn_closeConfirm">&times;</button>
                <h1 class="modal-title">Do You Want To Delete?</h1>
            </div>
            <div class="modal-body text-center">
                <h5>Are you sure want to delete this category</h5>
                <button class="btn btn-danger form-submit-btn" style="background:#3276b1; border-color:#3276b1">Yes</button>
                <button data-dismiss="modal" class="btn btn-danger form-submit-btn">No</button>
            </div>
        </div>

    </div>
</div>

@Html.Partial("~/Views/DeviceCategory/_AddCategory.cshtml")
@Html.Partial("~/Views/DeviceCategory/_editCategory.cshtml")



@section scripts
{
    <script src="~/Scripts/AppScript/category.js"></script>
    
}

CHL/CHL/Views/DeviceCategory/_AddCategory.cshtml
<div class="modal fade" id="add_category_model">
    <div class="modal-dialog">

        <form role="form" id="frmCategory" method="post" action="/DeviceCategory/AddCategory">
            <div class="modal-content">
                <div class="modal-header">
                    <button id="btn_close_category" type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title">Add Category</h4>
                </div>
                <div class="modal-body">

                    <div class="box-body">
                        <div class="form-group">
                            <input type="text" name="Name" class="form-control" id="InputcategoryName" placeholder="Enter Category Name">
                        </div>

                    </div>
                    <!-- /.box-body -->



                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button id="btn-category" type="submit" class="btn btn-primary">Add</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

CHL/CHL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/dataTableCss")
    @Styles.Render("~/Content/datapicker")
    
    <style>
        .loading {
            display: none;
        }
    </style>
    <link href="~/Content/loading.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

</head>
<body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper">

        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b>CHL</span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">

                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/Content/Img/user2-160x160.jpg" class="user-image" alt="User Image" />

                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">Test User</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/Content/Img/user2-160x160.jpg" class="img-circle" alt="User Image" />

                                    <p>
                                        Alexander Pierce - Web Developer
                                        <small>Member since Nov. 2012</small>
                                    </p>
                                </li>

                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Content/Img/user2-160x160.jpg" class="img-circle" alt="User Image" />

                    </div>
                    <div class="pull-left info">
                        <p>Alexander Pierce</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form (Optional) -->
                @*<form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>*@
                <!-- /.search form -->
                <!-- Sidebar Menu -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MENU</li>
                    <!-- Optionally, you can add icons to the links -->

                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-link"></i> <span>Device Category</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Category","DeviceCategory")">Category</a></li>
                            <li><a href="@Url.Action("Subcategory","DeviceCategory")">Sub category</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-link"></i> <span>Device</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("AddDevice","Device")">Add Device</a></li>
                            <li><a href="@Url.Action("ViewDevice","Device")">View Device</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-link"></i> <span>Software</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("AddSoftware","Software")">Add Sofware</a></li>
                            <li><a href="@Url.Action("ViewSoftware","Software")">View Sofware</a></li>
                        </ul>
                    </li>
                    @*<li class="active"><a href="#"><i class="fa fa-link"></i> <span>Link</span></a></li>
                    <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>*@
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">


            <!-- Main content -->
            <section class="content container-fluid">
                <!--------------------------
                | Your Page Content Here |
                -------------------------->
                @RenderBody()
            </section>

            <div class="loading" align="center">
                <img src="~/Content/Img/ajax-loader.gif" />
            </div>
            <div class="clearfix"></div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dataTable")
    @Scripts.Render("~/bundles/appscript")


    @RenderSection("scripts", required: false)
</body>
</html>